---
- name: Install Redis Stack Server using Docker
  hosts: all
  become: yes

  tasks:

    - name: Pull Redis Stack Docker image
      docker_image:
        name: redis/redis-stack
        tag: latest
        source: pull

    - name: Stop existing Redis Stack container (if running)
      docker_container:
        name: redis-stack
        state: stopped
      ignore_errors: yes

    - name: Remove existing Redis Stack container (if exists)
      docker_container:
        name: redis-stack
        state: absent
      ignore_errors: yes

    - name: Run Redis Stack container
      docker_container:
        name: redis-stack
        image: redis/redis-stack:latest
        state: started
        restart_policy: always
        ports:
          - "6379:6379"
          - "8001:8001"