---
- name: Install and run Rental Anshin Kun using Docker
  hosts: all
  become: yes

  tasks:
  
    - name: Pull Rental Anshin Kun Docker image
      docker_image:
        name: jiitakinc/rental-anshin-kun
        tag: latest
        source: pull

    - name: Stop existing Rental Anshin Kun container (if running)
      docker_container:
        name: rental-anshin-kun
        state: stopped
      ignore_errors: yes

    - name: Remove existing Rental Anshin Kun container (if exists)
      docker_container:
        name: rental-anshin-kun
        state: absent
      ignore_errors: yes

    - name: Run Rental Anshin Kun container
      docker_container:
        name: rental-anshin-kun
        image: jiitakinc/rental-anshin-kun:latest
        state: started
        restart_policy: always
        ports:
          - "6379:6379"
          - "8001:8001"