---
- name: Install and run Rental Anshin Kun using Docker
  hosts: all
  become: yes

  vars:
    docker_username: "{{ lookup('env', 'docker_username') }}"
    docker_password: "{{ lookup('env', 'docker_password') }}"

  tasks:
  
    - name: Docker login (if using private registry)
      docker_login:
        username: "{{ docker_username }}"
        password: "{{ docker_password }}"
        registry: "https://index.docker.io/v1/"
      when: docker_username is defined and docker_password is defined

    - name: Pull Rental Anshin Kun Docker image
      docker_image:
        name: jiitakinc/rental-anshin-kun
        tag: latest
        source: pull

    - name: Stop existing Rental Anshin Kun container (if running)
      docker_container:
        name: Rental-Dev
        state: stopped
      ignore_errors: yes

    - name: Remove existing Rental Anshin Kun container (if exists)
      docker_container:
        name: Rental-Dev
        state: absent
      ignore_errors: yes

    - name: Run Rental Anshin Kun container
      docker_container:
        name: rental-anshin-kun
        image: jiitakinc/rental-anshin-kun:latest
        state: started
        restart_policy: always
        ports:
          - "80:3000"