---
- name: Install Redis Stack Server using Docker
  hosts: all
  become: yes

  tasks:

    - name: Pull Redis Stack Docker image
      docker_image:
        name: rental
        tag: latest
        source: pull

    - name: Stop existing Redis Stack container (if running)
      docker_container:
        name: rental
        state: stopped
      ignore_errors: yes

    - name: Remove existing Redis Stack container (if exists)
      docker_container:
        name: rental
        state: absent
      ignore_errors: yes

    - name: Run Redis Stack container
      docker_container:
        name: rental
        image: jiitakinc/rental-anshin-kun:latest
        state: started
        restart_policy: always
        ports:
          - 3000