name: Deploy with Ansible

on:
  push

jobs:
  deploy:
    name: Deploy Ansible Playbook
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: "Install Ansible"
        uses: alex-oleshkevich/setup-ansible@VERSION 
        with:
          version: "9.3.0"

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Connect to EC2 and run script
        run: |
           ansible-playbook -i inventory.yml redis.yml