name: Deploy with Ansible

on:
  push

jobs:
  deploy:
    name: Deploy Ansible Playbook
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          # Required, playbook filepath
          playbook: redis.yml
          # Optional, directory where playbooks live
          directory: ./Redis
          # Optional, SSH private key
          key: ${{secrets.SSH_PRIVATE_KEY}}
          options: 
            --ssh-extra-args "-o StrictHostKeyChecking=no"
            --extra-vars "docker_username=${{ secrets.DOCKER_USERNAME }} docker_password=${{ secrets.DOCKER_PASSWORD }}"
          inventory: |
            54.204.241.153 ansible_user=ubuntu